config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :households do
    resources :expenses
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'households#index'

  post 'expenses/monthlystatementoutput'
  get 'expenses/monthlyinput'

  post 'expenses/monthly_table'

  get 'categories/create'
  post 'categories/create'
  get 'categories/update'
  post 'categories/add_to_household'
  get 'categories/destroy'

  post 'categories/add_to_expense'
  delete 'categories/delete_from_expense'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :expense_categories
  has_many :expenses, through: :expense_categories
  has_many :household_categories
  has_many :households, through: :household_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_household, only: [:index, :create, :add_to_household]

  def index

  end

  def create

    @category = @household.categories.new(category_params)
    puts @category.name
    begin
      @category.save
      @household.categories << @category
      @message = 'Category successfully . . . '
    rescue ActiveRecord::RecordNotUnique => e
      puts e.to_s
      @message = ' The desired category is already available'
    end
    respond_to do |format|
      format.js
    end
  end

  def add_to_household
    puts '~~~~~~~~~~~~~~~~~~~~'
    puts add_category_params
    puts add_category_params[:category_id].to_i.class
    i = add_category_params[:category_id]
    i = i.to_i
    puts i
    puts i.class
    c = Category.find i
    puts 'c:'
    puts c.name
    puts c.id
    puts '~~~~~~~~~~~~~~~~~~~~'
    @household.categories << c
    @c = c
  end

  def add_to_expense

    i = add_category_params[:category_id]
    i = i.to_i
    e = add_category_params[:expense_id]
    e = e.to_i
    category = Category.find i
    expense = Expense.find e
    if expense.categories << category
      @category = category
    else
      puts 'no no no'
    end
  end

  def delete_from_expense
    cat_id = add_category_params[:category_id]
    cat_id = cat_id.to_i
    ex_id = add_category_params[:expense_id]
    ex_id = ex_id.to_i
    e = Expense.find(ex_id)
    e.categories.delete(cat_id)
    @e = e
    @cat_id = cat_id
  end

  def update
  end

  def destroy
  end

  private

  def set_household
    @household = Household.find(params[:household_id])
  end

  def category_params
    params.permit(:name)
  end

  def add_category_params
    params.permit(:name, :household_id, :category_id, :expense_id)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_add_cat_after_add.html.erb
<% expense.categories.each do |c| %>
  <%= form_tag categories_delete_from_expense_path, method: :delete, remote: true do %>
    <div id="cat-<%= c.id %>">
      <%= c.name %>
      <%= hidden_field_tag :household_id, @household.id %>
      <%= hidden_field_tag :category_id, c.id %>
      <%= hidden_field_tag :name, c.name %>
      <%= hidden_field_tag :expense_id, @expense.id %>
      <small><%= submit_tag 'remove', class: 'btn btn-sm btn-outline-danger' %></small>
    </div>
  <% end %>
<% end %>

app/views/categories/_form.html.erb
<%= form_tag categories_create_path, remote: true do %>
    <div class="form-group mr-sm-5">
      <%= label_tag :category %>
      <%= text_field_tag :name,'', placeholder: 'Lebensmittel', class: 'form-control' %>
    </div>
    <%= hidden_field_tag :household_id, @household.id %>
    <div class="actions">
      <%= submit_tag :hopp, class: 'btn btn-sm btn-outline-success' %>
    </div>
<% end %>

app/views/categories/_index.html.erb
<div>
  <%= @message %>
</div>

app/views/categories/_list.html.erb
<div class="container">
  <%= render 'categories/form' %>
</div>
<div class="row">
  <div class="col-md mt-3">
    <div>
      <b>household categories:</b>
    </div>
    <% @added_categories.each do |cat| %>
        <div>
          <%= cat.name %>
        </div>
    <% end %>
    <div id="new_category"></div>
  </div>
  <div class="col-md mt-3">
    <div>
      <b>also available:</b>
    </div>
    <% @also_categories.each do |cat| %>
        <div>

          <%= form_tag categories_add_to_household_path, remote: true, class: 'form-inline' do %>

              <%= hidden_field_tag :household_id, @household.id %>
              <%= hidden_field_tag :category_id, cat.id %>
              <%= hidden_field_tag :name, cat.name %>
              <span><%= submit_tag 'add', class: 'btn btn-sm btn-outline-secondary', style: 'font-size: 10px;' %></span>
              &nbsp;<%= cat.name %>
          <% end %>
        </div>
    <% end %>
  </div>
</div>
<div class="container" id="category">

</div>

app/views/categories/add_to_expense.js.erb
$('#new_expense_category').append('<%= @category.name %>');

app/views/categories/add_to_household.js.erb
$('#new_category').append('<%= @c.name %>');

app/views/categories/create.js.erb
$('#category').append('<%= j render 'categories/index' %>');

app/views/categories/delete_from_expense.js.erb
$('#cat-<%= @cat_id %>').remove();

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>