config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :households do
    resources :expenses
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'households#index'

  post 'expenses/monthlystatementoutput'
  get 'expenses/monthlyinput'

  post 'expenses/monthly_table'

  get 'categories/create'
  post 'categories/create'
  get 'categories/update'
  post 'categories/add_to_household'
  get 'categories/destroy'

  post 'categories/add_to_expense'
  delete 'categories/delete_from_expense'

end

app/models/monthly.rb
class Monthly
  attr_accessor :month, :bill, :year, :categories

  def initialize(month, year, categories)
    @month= month
    @year = year
    @bill = 0
    @categories = categories
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_household, only: [:index, :new, :create, :edit, :update, :monthlystatementoutput, :monthlyinput, :monthly_table]
  before_action :authenticate_user!
  before_action :require_household_user, only: [:index]

  # GET /expenses
  # GET /expenses.json
  def index
    d = Date.today
    @expenses = @household.expenses.monthly_statement(d.month, d.year).order(spent_at: :desc)
  end

  def monthly_table
    m = params[:month]
    y = params[:year]
    @expenses = @household.expenses.monthly_statement(m, y).order(spent_at: :desc)
    respond_to do |format|
      format.js
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  def monthlystatementoutput

    categories = []
    @monthly = Monthly.new(params[:month], params[:year], categories)
    monthly_expenses = @household.expenses.monthly_statement(params[:month], params[:year])
    monthly_expenses.each do |e|
      @monthly.bill += e.amount
      e.categories.each do |category|
        categories.push category
        categories.uniq!
      end
    end

    catEx = {}
    categories.each do |cat|
      e = 0
      monthly_expenses.each do |me|
        if me.categories.include? cat
          puts cat.name + ' ' + me.amount.to_s
          e += me.amount
        end
      end
      cH = {cat.name => e}
      catEx.merge! cH
    end
    @catEx = catEx
    puts @catEx.inspect
    respond_to do |format|
      format.js
    end
  end

  def monthlyinput

  end

  # GET /expenses/new
  def new
    @expense = @household.expenses.new
    @household_categories = @household.categories
  end

  # GET /expenses/1/edit
  def edit
    @expense = @household.expenses.find(params[:id])
    if current_user != @expense.user
      flash[:danger] = 'you have no permission to do this'
      redirect_to root_url
    end
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = @household.expenses.new(expense_params)
    @expense.user_id = current_user.id
    if @expense.save
      flash[:success] = 'Expense was successfully created.'

      puts 'cat_params:'
      puts cat_params[:category]
      puts cat_params[:category].class

      if cat_params[:category] == ''
        c = Category.find_by_name('miscellaneous')
      else
        c = Category.find cat_params[:category].to_i
      end

      @expense.categories << c

      ActionCable.server.broadcast "household_#{@household.id}_expenses",
                                   household: @household.id,
                                   amount: @expense.amount,
                                   description: @expense.description,
                                   user: @expense.user.username
      # head :ok

      redirect_to household_expenses_path(@household)
    else
      flash[:alert] = "That wasn't what you'd expected, right?"
      redirect_to root_url
    end

  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    @expense = @household.expenses.find(params[:id])
    respond_to do |format|
      if @expense.update(expense_params)

        # c = Category.find cat_params[:category].to_i
        #
        # if @expense.categories << c
        #   puts 'SUPER'
        # else
        #   puts 'SCHEIßE'
        # end

        flash[:alert] = 'Expense was successfully updated.'
        format.html {redirect_to household_expenses_path(@household)}
        format.json {render :show, status: :ok, location: @expense}
      else
        format.html {render :edit}
        format.json {render json: @expense.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html {redirect_to expenses_url, notice: 'Expense was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def expense_params
    params.require(:expense).permit(:amount, :description, :spent_at)
  end

  def cat_params
    params.permit(:category)
  end

  def set_household
    @household = Household.find(params[:household_id])
  end

  def household_params
    params.require(:household).permit(:name)
  end

end

app/helpers/expenses_helper.rb
module ExpensesHelper

  def fix_it(amount)
    sprintf '%.2f', amount
  end

  def month_name(month)
    case month
      when '1' then
        'Januar'
      when '2' then
        'Februar'
      when '3' then
        'März'
      when '4' then
        'April'
      when '5' then
        'Mai'
      when '6' then
        'Juni'
      when '7' then
        'Juli'
      when '8' then
        'August'
      when '9'
        'September'
      when '10' then
        'Oktober'
      when '11' then
        'November'
      when '12' then
        'Dezember'
    end
  end

end

app/views/expenses/monthly/_expenses_table.html.erb
<table class="table table-hover table-sm">
  <thead>
  <th class="text-right pr-md-3"><small>Amount</small></th>

  <th class="pl-md-3"><small>Description</small></th>
  <th><small>Spent at</small></th>
  <th></th>
  <th></th>
  </thead>

  <% @expenses.each do |expense| %>
    <tr>
      <td class="col-sm-1 text-sm-right pr-md-3" id="amount-<%= expense.id %>"><%= fix_it(expense.amount) %></td>

      <td class="col-sm-2 text-sm-left pl-md-3"><%= expense.description %></td>
      <td class="col-sm-1 text-sm-center"><%= expense.spent_at.strftime('%d.%m.%y') %></td>
      <td class="col-sm-1">
        <% expense.categories.each do |category| %>
          <small><%= category.name %></small>
        <% end %>
      </td>
      <td class="col-sm-1 text-sm-right">
        <small><%= link_to 'Edit', edit_household_expense_path(@household, expense) %></small>
      </td>
    </tr>
  <% end %>
</table>

app/views/expenses/monthly/_monthly_bill.html.erb
<div class="card mb-sm-3 mt-sm-3">
  <div class="card-body">
    <div>
      <b><%= month_name @monthly.month %> <%= @monthly.year %></b>
    </div>
  </div>
  <div class="card-body">
    <table class="table-responsive table-bordered table-sm">
      <tr>
        <th class="pr-md-3">
          <small>category</small>
        </th>
        <th class="pl-md-3">
          <small>sum</small>
        </th>
      </tr>
      <% @catEx.each do |k, v| %>
        <tr>
          <td class="pr-md-3"><%= k %></td>
          <td class="text-right pl-md-3"><%= fix_it v %></td>
        </tr>
      <% end %>
    </table>

    <div class="mt-md-3">
      total: <%= fix_it(@monthly.bill) %>
    </div>

  </div>
</div>

app/views/expenses/monthly/_monthly_form.html.erb
<%= form_tag expenses_monthlystatementoutput_path, class: 'form-inline', remote: true do %>
  <div class="form-group col-md-2 mx-sm-1">
    <%#= label_tag :month, 'Month' %>
    <%= text_field_tag :month, '1', class: 'form-control' %>
  </div>
  <div class="form-group col-md-3 mx-sm-1">
    <%= text_field_tag :year, '2018', class: 'form-control' %>
  </div>
  <%= hidden_field_tag 'household_id', @household.id %>
  <div class="form-group col-md-2 mx-sm-1">
    <%= submit_tag 'yepp', class: 'btn btn-sm btn-outline-dark' %>
  </div>

<% end %>

app/views/expenses/monthly/_monthly_table_form.html.erb
<%= form_tag expenses_monthly_table_path, class: 'form-inline', remote: true do %>
  <div class="form-group">
    <%#= label_tag :month, 'Month' %>
    <%= text_field_tag :month, '1', class: 'form-control', size: 2, style: 'font-size: 10px' %>
  </div>
  <div class="form-group mx-sm-1">
    <%= text_field_tag :year, '2018', class: 'form-control', size: 5, style: 'font-size: 10px' %>
  </div>
  <%= hidden_field_tag 'household_id', @household.id %>
  <div class="form-group">
    <%= submit_tag 'yepp', class: 'btn btn-sm btn-outline-dark', style: 'font-size: 10px' %>
  </div>
<% end %>