config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :households do
    resources :expenses
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'households#index'

  post 'expenses/monthlystatementoutput'
  get 'expenses/monthlyinput'

  post 'expenses/monthly_table'

  get 'categories/create'
  post 'categories/create'
  get 'categories/update'
  post 'categories/add_to_household'
  get 'categories/destroy'

  post 'categories/add_to_expense'
  delete 'categories/delete_from_expense'

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_household, only: [:index, :new, :create, :edit, :update, :monthlystatementoutput, :monthlyinput, :monthly_table]
  before_action :authenticate_user!
  before_action :require_household_user, only: [:index]

  # GET /expenses
  # GET /expenses.json
  def index
    d = Date.today
    @expenses = @household.expenses.monthly_statement(d.month, d.year).order(spent_at: :desc)
  end

  def monthly_table
    m = params[:month]
    y = params[:year]
    @expenses = @household.expenses.monthly_statement(m, y).order(spent_at: :desc)
    respond_to do |format|
      format.js
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  def monthlystatementoutput

    categories = []
    @monthly = Monthly.new(params[:month], params[:year], categories)
    monthly_expenses = @household.expenses.monthly_statement(params[:month], params[:year])
    monthly_expenses.each do |e|
      @monthly.bill += e.amount
      e.categories.each do |category|
        categories.push category
        categories.uniq!
      end
    end

    catEx = {}
    categories.each do |cat|
      e = 0
      monthly_expenses.each do |me|
        if me.categories.include? cat
          puts cat.name + ' ' + me.amount.to_s
          e += me.amount
        end
      end
      cH = {cat.name => e}
      catEx.merge! cH
    end
    @catEx = catEx
    puts @catEx.inspect
    respond_to do |format|
      format.js
    end
  end

  def monthlyinput

  end

  # GET /expenses/new
  def new
    @expense = @household.expenses.new
    @household_categories = @household.categories
  end

  # GET /expenses/1/edit
  def edit
    @expense = @household.expenses.find(params[:id])
    if current_user != @expense.user
      flash[:danger] = 'you have no permission to do this'
      redirect_to root_url
    end
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = @household.expenses.new(expense_params)
    @expense.user_id = current_user.id
    if @expense.save
      flash[:success] = 'Expense was successfully created.'

      puts 'cat_params:'
      puts cat_params[:category]
      puts cat_params[:category].class

      if cat_params[:category] == ''
        c = Category.find_by_name('miscellaneous')
      else
        c = Category.find cat_params[:category].to_i
      end

      @expense.categories << c

      ActionCable.server.broadcast "household_#{@household.id}_expenses",
                                   household: @household.id,
                                   amount: @expense.amount,
                                   description: @expense.description,
                                   user: @expense.user.username
      # head :ok

      redirect_to household_expenses_path(@household)
    else
      flash[:alert] = "That wasn't what you'd expected, right?"
      redirect_to root_url
    end

  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    @expense = @household.expenses.find(params[:id])
    respond_to do |format|
      if @expense.update(expense_params)

        # c = Category.find cat_params[:category].to_i
        #
        # if @expense.categories << c
        #   puts 'SUPER'
        # else
        #   puts 'SCHEIßE'
        # end

        flash[:alert] = 'Expense was successfully updated.'
        format.html {redirect_to household_expenses_path(@household)}
        format.json {render :show, status: :ok, location: @expense}
      else
        format.html {render :edit}
        format.json {render json: @expense.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html {redirect_to expenses_url, notice: 'Expense was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def expense_params
    params.require(:expense).permit(:amount, :description, :spent_at)
  end

  def cat_params
    params.permit(:category)
  end

  def set_household
    @household = Household.find(params[:household_id])
  end

  def household_params
    params.require(:household).permit(:name)
  end

end

app/helpers/expenses_helper.rb
module ExpensesHelper

  def fix_it(amount)
    sprintf '%.2f', amount
  end

  def month_name(month)
    case month
      when '1' then
        'Januar'
      when '2' then
        'Februar'
      when '3' then
        'März'
      when '4' then
        'April'
      when '5' then
        'Mai'
      when '6' then
        'Juni'
      when '7' then
        'Juli'
      when '8' then
        'August'
      when '9'
        'September'
      when '10' then
        'Oktober'
      when '11' then
        'November'
      when '12' then
        'Dezember'
    end
  end

end

app/views/expenses/_form.html.erb
<%= form_for(expense, url: {action: create_or_update}, local: true) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <div><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</div>

      <ul>
        <% expense.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :expense_amount, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :expense_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <small>
      <%#= form.label :spent_at %>
      <%= form.datetime_select :spent_at, id: :expense_spent_at, class: 'btn btn-outline-primary' %>
    </small>
  </div>

  <% if create_or_update == 'create' %>
    <div class="form-group">
      <%= select_tag 'category', options_from_collection_for_select(@household_categories, 'id', 'name', '16'), class: 'form-control', include_blank: true %>
    </div>

  <% end %>

  <div>
    <%= form.submit :hopp, class: 'btn btn-outline-success' %>
  </div>
<% end %>

<div class="row mt-lg-3">

  <% if create_or_update == 'update' %>
    <div class="col-md" id="new_expense_category">
      <% @expense.categories.each do |c| %>
        <%= form_tag categories_delete_from_expense_path, method: :delete, remote: true do %>
          <div id="cat-<%= c.id %>">
            <%= hidden_field_tag :household_id, @household.id %>
            <%= hidden_field_tag :category_id, c.id %>
            <%= hidden_field_tag :name, c.name %>
            <%= hidden_field_tag :expense_id, @expense.id %>
            <small>
              <%= submit_tag 'remove', class: 'btn btn-sm btn-outline-danger', style: 'font-size: 10px' %>
              <%= c.name %>
            </small>
          </div>
        <% end %>
      <% end %>
    </div>
    <div></div>
    <div class="col-md">
      <% @household.categories.each do |a| %>
        <%= form_tag categories_add_to_expense_path, remote: true do %>
          <%= hidden_field_tag :household_id, @household.id %>
          <%= hidden_field_tag :category_id, a.id %>
          <%= hidden_field_tag :name, a.name %>
          <%= hidden_field_tag :expense_id, @expense.id %>
          <small>
            <%= submit_tag 'add', class: 'btn btn-sm btn-outline-secondary', style: 'font-size: 10px' %>
            <%= a.name %>
          </small>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/expenses/_monthly.html.erb
<div class="row">
  <div class="col-md">
    <%= render 'expenses/monthly/monthly_form' %>
  </div>
</div>
<div class="row">
  <div class="col-md">
    <span id="monthly">

    </span>
  </div>
</div>

app/views/expenses/edit.html.erb
<h4>Editing Expense</h4>

<%= render 'form', expense: @expense, household: @household, create_or_update: 'update' %>
<br>
<%= link_to 'Show', household_expenses_path(household_id: @household.id) %>
<%= link_to 'Back', household_expenses_path %>

app/views/expenses/index.html.erb
<div class="mx-sm-2">
  <div class="row">
    <div class="col-md">
      <h4><%= @household.name %></h4>
    </div>
    <div class="col-md">
      <%= link_to 'New Expense', new_household_expense_path %>
      <small><%= link_to 'edit household', household_path(@household) %></small>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md">
      <div id="new_expense" data-channel="new_expense" data-household-id="<%= @household.id %>"></div>
      <div>
        <%= render 'expenses/monthly/monthly_table_form' %>
      </div>
      <div id="monthly_table">
        <%= render 'expenses/monthly/expenses_table' %>
      </div>
    </div>
    <div class="col-md">
      <div>
        <%= render 'expenses/monthly', household_id: @household.id %>
      </div>

    </div>
  </div>

  <div class="row">
    <!--<div class="col-md-2"><%#= link_to 'Show', expense %></div>

    <div class="col-md-2"><%#= link_to 'Destroy', expense, method: :delete, data: {confirm: 'Are you sure?'} %></div>
-->

  </div>
</div>

<style>
</style>

app/views/expenses/monthly_table.js.erb
$('#monthly_table').html('');
$('#monthly_table').append('<%= j render 'expenses/monthly/expenses_table' %>').fadeIn(1200);

app/views/expenses/monthlystatementoutput.js.erb
$('#monthly').html('');
$('#monthly').append('<%= j render 'expenses/monthly/monthly_bill' %>');

app/views/expenses/new.html.erb
<div class="container">
  <br>
  <div class="row">
    <h5>New Expense for <%= @household.name %></h5>
  </div>

  <br>

  <div class="row">
    <div class="col-md-6">
      <%= render 'form', expense: @expense, create_or_update: 'create' %>
    </div>
  </div>

  <br>
  <div class="row">
    <%= link_to 'Back', household_expenses_path %>
  </div>
</div>
<br><br>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Spent at:</strong>
  <%= @expense.spent_at %>
</p>

<%#= link_to 'Edit', edit_expense_path(@expense) %> |
<%#= link_to 'Back', expenses_path %>